" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
let g:netrw_banner=0
let g:netrw_bufsettings='noma nomod nu nobl nowrapp ro'
let g:netrw_list_hide='^\.[^.]\+'
let g:ycm_confirm_extra_conf=0
let g:python3_host_prog='/usr/bin/python'
set mouse=a
set laststatus=2
set noequalalways
set number
set tabstop=4
set shiftwidth=4
set shellcmdflag=-ic
set ignorecase
set smartcase

packadd termdebug

