" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
let g:netrw_banner=0
let g:netrw_bufsettings='noma nomod nu nobl nowrapp ro'
let g:netrw_list_hide='^\.[^.]\+'
let g:ycm_confirm_extra_conf=0
let g:python3_host_prog='/usr/bin/python'
set mouse=a
set laststatus=2
set noequalalways
set number
set tabstop=4
set shiftwidth=4
set ignorecase
set smartcase

packadd termdebug

set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=/etc/vim/bundle/Vundle.vim
call vundle#begin('/etc/vim/bundle')

Plugin 'VundleVim/Vundle.vim'
Plugin 'DrawIt'
Plugin 'godlygeek/tabular'
Plugin 'pangloss/vim-javascript'
Plugin 'raimondi/delimitmate'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'unblevable/quick-scope'
Plugin 'valloric/youcompleteme'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on
let NERDTreeShowLineNumbers=1

" Bindings
map <F1> :let $VIM_DIR=expand("%:p:h")<CR>:term<CR>clear&&cd $VIM_DIR<CR>
map <F2> :let $VIM_DIR=expand("%:p:h")<CR>:vert term<CR>clear&&cd $VIM_DIR<CR>
map <F5> :let $VIM_DIR=expand("%:p:h")<CR>:let $VIM_FILE=expand("%")<CR>:term<CR>clear&&cd $VIM_DIR&&make&&./main<CR>
map <F6> :let $VIM_DIR=expand("%:p:h")<CR>:let $VIM_FILE=expand("%")<CR>:term<CR>clear&&cd $VIM_DIR&&python $VIM_FILE<CR>

" Startup
autocmd  VimEnter * NERDTree | wincmd p
